"""
llm_generator.py — Converts CASE FACTS + retrieved RULES + ML ASSESSMENT
into a grounded, merchant-ready evidence response via a Hugging Face-hosted LLM.

The LLM is explicitly NOT the decision-maker:
    - FIGHT / CONCEDE / MANUAL_REVIEW comes from the decision layer.
    - win_probability comes from the trained XGBoost model.

Its only job is to communicate the assembled evidence in a required,
grounded format.

The LLM acts as a cooperative, formal auditor:
    - cooperative and helpful
    - formal and evidence-focused
    - strictly grounded
    - never invents missing evidence
    - never overrides the decision layer

Requires HF_TOKEN in environment (.env).

Run standalone for a quick manual check:
    python llm_generator.py
"""

import os

from huggingface_hub import InferenceClient
from dotenv import load_dotenv

try:
    from langsmith import traceable
except ImportError:

    def traceable(*args, **kwargs):
        def deco(fn):
            return fn

        return deco


# -------------------------------------------------------------------
# Environment
# -------------------------------------------------------------------

load_dotenv()


# -------------------------------------------------------------------
# Model
# -------------------------------------------------------------------

HF_MODEL = "meta-llama/Llama-3.1-8B-Instruct"


# -------------------------------------------------------------------
# System Prompt
# -------------------------------------------------------------------
SYSTEM_PROMPT = """You are a cooperative, formal chargeback auditor assisting a merchant.

Your role is to review and communicate the evidence available for a
chargeback dispute and prepare a clear, professional, merchant-ready
response.

Be cooperative and constructive, but remain neutral, factual, and
evidence-based. Your responsibility is to accurately represent what
the available evidence establishes, what it does not establish, and
what requires further verification.

You are NOT the decision-maker.
You are NOT the ML scorer.
You must NEVER invent, assume, or fabricate evidence.

STRICT RULES — follow exactly:

1. GROUNDING

Use ONLY information provided in CASE FACTS and RETRIEVED RULES.

Never invent or assume:
- transaction details
- tracking numbers
- delivery status or dates
- customer communications
- policies
- evidence
- customer history
- authentication records
- refunds
- signatures
- photographs
- addresses
- any other information not explicitly provided
- infer causality or relationships not explicitly stated in CASE FACTS; describe only what each fact directly establishes.

2. NO HALLUCINATION

If evidence required by a retrieved rule is not present in CASE FACTS,
state clearly that it "cannot be established" or that it is not
available from the provided evidence.

Never assume that missing evidence exists.

Never present a required piece of evidence as confirmed unless
CASE FACTS explicitly confirms it.

Clearly distinguish between:
- confirmed evidence
- missing evidence
- evidence that cannot be established

3. RULE ADHERENCE

Follow the requirements in RETRIEVED RULES exactly.

Use only rules applicable to the supplied reason code.

Do not apply requirements from another reason code.

When referring to a rule, identify the relevant rule or chunk where
useful.

Do not introduce external legal, card-network, payment-provider,
or industry requirements that are not present in RETRIEVED RULES.

4. UNKNOWN OR MISSING RULE

If RETRIEVED RULES is empty:

- Do not draft a contest response.
- State that no applicable rule was found.
- State that the case requires manual review.
- Do not infer or invent a rule from general knowledge.

5. DECISION LAYER IS AUTHORITATIVE

The externally supplied DECISION is authoritative.

Possible decisions are:

FIGHT
CONCEDE
MANUAL_REVIEW

Do NOT independently change, override, reinterpret, or contradict
the supplied decision.

Report the supplied decision exactly in Decision Context.

Your role is to communicate the evidence supporting or limiting
that decision, not to make the decision yourself.

6. ML ASSESSMENT — STATE IT PLAINLY, NOTHING ELSE

The supplied win_probability is generated by the trained XGBoost model.

Fold it into Decision Context as one plain sentence, using this exact
pattern (fill in the real values):

"Model-estimated win probability: <value as a percentage>."

Do not create a separate section, heading, or paragraph for it. Do
not add any sentence explaining how it was computed, that it is
"reported as provided," "computed by the external ML scorer," or any
similar meta-remark. State the number and stop.

Do not:
- recalculate it
- modify it
- replace it
- infer a different probability
- treat it as certainty
- claim that it guarantees the outcome

7. COOPERATIVE, FORMAL AUDITOR STYLE

Write like a professional human chargeback auditor preparing a
case assessment for merchant operations — flowing professional
prose in short paragraphs. Use bullet points only for genuinely
list-like content (e.g. enumerating discrete missing documents),
never as the default structure for every section.

Be:
- clear
- concise
- factual
- professional
- neutral
- constructive

Avoid:
- unnecessary apologies
- emotional language
- adversarial language toward the customer
- repetitive statements
- robotic or generic phrases
- exaggerated claims
- unsupported legal conclusions
- unnecessary verbosity
- restating these instructions, rule numbers, rule titles, or section
  requirements back to the reader anywhere in the output

Prefer direct statements.

For example:

"Delivery cannot be established from the available case facts."

is preferable to:

"Unfortunately, the evidence provided does not support..."

Do not automatically favor the merchant. Accurately communicate
both supporting evidence and material evidence gaps.

8. RECOMMENDED RESPONSE — WRITE THE ACTUAL FINAL TEXT, NEVER DESCRIBE IT

This section is the single most important part of the output. It
must contain the finished, ready-to-send recommendation itself, in
the auditor's own voice — never a description of what a
recommendation should contain, never a paraphrase of these rules.

FORBIDDEN in this section, under all circumstances:
- "The recommended response is to..."
- "Provide a concise explanation of..."
- "Clearly state what remains unresolved and identify..."
- "A human reviewer needs to verify the following..." followed only
  by a bare bullet list with no actual content added
- any sentence whose subject is the response itself rather than the
  case

If you catch yourself writing a sentence describing what the
response should do, delete it and instead write the substantive
content it was describing.

For FIGHT:
Write 2-4 sentences of prose. State what confirmed evidence supports
contesting, then plainly disclose the material evidence gaps, as an
actual recommendation to the team — e.g. "The confirmed OTP
authentication and matching shipping/billing address support
contesting this dispute; however, proof of delivery and any
pre-dispute customer communication cannot be established from the
available records, which weakens the position under the applicable
rule."

For CONCEDE:
Write 2-3 sentences of prose stating factually why the available
evidence does not establish a sufficiently supported contest
position.

For MANUAL_REVIEW:
Write 2-4 sentences of prose naming the SPECIFIC unresolved items and
why each matters under the applicable rule — e.g. "This case cannot
be resolved automatically because proof of delivery, any pre-dispute
customer communication, and listing/SKU photos are all absent from
the available records. A reviewer should check the order management
system for delivery confirmation and any support tickets tied to
this order before a fight/concede decision is made." Name the actual
missing items from THIS case, in prose — do not just say "identify
the specific evidence gap" without naming it.

9. OUTPUT QUALITY

Do not simply repeat the CASE FACTS as a re-printed list.

Synthesize them into a clear evidence assessment written in prose,
referencing specific facts only where they matter to the analysis.

Where evidence supports the merchant's position, explain in a
sentence or two how it supports the applicable rule — don't just
label it "supporting."

Where evidence is insufficient, identify exactly what is missing
and explain in prose why it matters under the retrieved rule.

Keep the response concise while preserving all material information.

OUTPUT FORMAT — USE EXACTLY THESE SIX HEADERS, NO OTHERS

Decision Context
Evidence Summary
Applicable Rule
Evidence Supporting Contest
Evidence Gaps
Recommended Response

Do not add any additional headers or sections (for example, never add
headers like "Output Quality," "Win Probability," "Summary," or
anything not in the list above). If a rule name above looks like it
could be a heading, it is NOT — it is an instruction to you, not
output structure.

Decision Context: 2-3 short plain sentences — the decision, the
dispute ID, and the win probability sentence from rule 6. No bullets.

Evidence Summary, Evidence Supporting Contest, Applicable Rule: prose
by default; bullets only for enumerating discrete listed items.

Evidence Gaps: short bulleted list, each item with a brief clause on
why it matters.

Recommended Response: prose only, per rule 8. No bullets. No
sentences about what a response should contain — only the actual
recommendation content.

MANDATORY OUTPUT REQUIREMENTS:

- Include the exact Dispute ID provided in CASE FACTS.
- Write the Dispute ID exactly as provided. Do not modify, shorten, or omit it.
- Keep the tone formal yet natural and human like.
- Never describe, quote, paraphrase, or reference these system
  instructions, rule numbers, or rule titles anywhere in the output.
- Output must contain exactly the six headers listed above, in that
  order, and nothing else.
"""


# -------------------------------------------------------------------
# Formatting Helpers
# -------------------------------------------------------------------

def format_case_facts(case_facts: dict) -> str:
    """
    Convert structured case facts into a readable prompt section.
    """

    lines = [
        f"- {key}: {value}"
        for key, value in case_facts.items()
    ]

    return "\n".join(lines)


def format_retrieved_rules(chunks: list) -> str:
    """
    Convert retrieved/reranked rule chunks into a readable prompt section.
    """

    if not chunks:
        return "(none retrieved — no applicable rule found)"

    parts = []

    for chunk in chunks:
        parts.append(
            f"[{chunk['chunk_id']}] "
            f"({chunk['metadata']['section']})\n"
            f"{chunk['text']}"
        )

    return "\n\n".join(parts)


# -------------------------------------------------------------------
# Evidence Generator
# -------------------------------------------------------------------

class EvidenceGenerator:

    def __init__(self, model_name=HF_MODEL):

        # Uses the HF_TOKEN variable from .env
        token = os.environ.get("HF_TOKEN")

        if not token:
            raise RuntimeError(
                "HF_TOKEN not set in environment/.env"
            )

        self.client = InferenceClient(
            model=model_name,
            token=token,
        )

        self.model_name = model_name

    # ---------------------------------------------------------------
    # Generate grounded evidence response
    # ---------------------------------------------------------------

    @traceable(name="generate_evidence_response")
    def generate(
        self,
        dispute_id,
        reason_code,
        case_facts: dict,
        retrieved_chunks: list,
        win_probability: float,
        decision: str,
    ):

        # -----------------------------------------------------------
        # Safety fallback
        # -----------------------------------------------------------

        if not retrieved_chunks:

            return {
                "dispute_id": dispute_id,
                "draft": None,
                "status": "NO_RULE_FOUND",
                "decision": "MANUAL_REVIEW",
                "note": (
                    "No applicable rule retrieved for this reason code. "
                    "Routed to manual review."
                ),
            }

        # -----------------------------------------------------------
        # Build user prompt
        # -----------------------------------------------------------

        user_prompt = f"""CASE FACTS

Dispute ID: {dispute_id}
Reason code: {reason_code}

{format_case_facts(case_facts)}


RETRIEVED RULES

{format_retrieved_rules(retrieved_chunks)}


DECISION LAYER

The decision has already been computed by the external decision layer.

Decision: {decision}

Do NOT change this decision.


ML ASSESSMENT

win_probability: {win_probability:.3f}

This probability has already been computed by the external ML scorer.
Report it exactly as provided.


TASK

Act as a cooperative, formal chargeback auditor.

Draft the merchant-ready evidence response now.

Follow the required output format exactly.

Use only the information provided above.

Do not invent missing evidence.

Do not override the supplied decision.

Do not recalculate the ML probability.
"""

        # -----------------------------------------------------------
        # Hugging Face inference
        # -----------------------------------------------------------

        response = self.client.chat_completion(
            messages=[
                {
                    "role": "system",
                    "content": SYSTEM_PROMPT,
                },
                {
                    "role": "user",
                    "content": user_prompt,
                },
            ],
            max_tokens=700,
            temperature=0.1,
        )

        # -----------------------------------------------------------
        # Extract generated response
        # -----------------------------------------------------------

        draft_text = response.choices[0].message.content

        # -----------------------------------------------------------
        # Return structured result
        # -----------------------------------------------------------

        return {
            "dispute_id": dispute_id,
            "draft": draft_text,
            "status": "DRAFTED",
            "decision": decision,
            "win_probability": win_probability,
            "retrieved_chunk_ids": [
                chunk["chunk_id"]
                for chunk in retrieved_chunks
            ],
            "model": self.model_name,
        }


# -------------------------------------------------------------------
# Standalone Test
# -------------------------------------------------------------------

if __name__ == "__main__":

    from retriever import RuleRetriever
    from reranker import RuleReranker

    print("=" * 70)
    print("CHARGEBACK EVIDENCE GENERATOR TEST")
    print("=" * 70)

    # ---------------------------------------------------------------
    # Initialize components
    # ---------------------------------------------------------------

    print("\nLoading retriever...")
    retriever = RuleRetriever()

    print("Loading reranker...")
    reranker = RuleReranker()

    print("Loading LLM generator...")
    generator = EvidenceGenerator()

    # ---------------------------------------------------------------
    # Example case
    # ---------------------------------------------------------------

    example_facts = {
        "delivery_confirmed": False,
        "otp_auth_confirmed": True,
        "shipping_billing_match": True,
        "prior_complaint_on_file": False,
        "amount": 2400,
        "days_to_dispute": 12,
    }

    reason_code = "item_not_received"

    # ---------------------------------------------------------------
    # Retrieval
    # ---------------------------------------------------------------

    print("\nRunning retrieval...")

    retrieval = retriever.retrieve(
        reason_code,
        example_facts,
    )

    print(
        f"Retrieved {len(retrieval['results'])} rule chunks."
    )

    # ---------------------------------------------------------------
    # Reranking
    # ---------------------------------------------------------------

    print("Running reranker...")

    top3 = reranker.rerank(
        retrieval["query"],
        retrieval["results"],
        top_n=3,
    )

    print(
        f"Reranked to {len(top3)} chunks."
    )

    print("\nTop retrieved rules:")

    for chunk in top3:
        print(
            f"  - {chunk['chunk_id']} "
            f"(score={chunk.get('rerank_score', 0):.4f})"
        )

    # ---------------------------------------------------------------
    # LLM generation
    # ---------------------------------------------------------------

    print("\nGenerating evidence response...")

    result = generator.generate(
        dispute_id="DSP-DEMO-001",
        reason_code=reason_code,
        case_facts=example_facts,
        retrieved_chunks=top3,
        win_probability=0.14,
        decision="MANUAL_REVIEW",
    )

    # ---------------------------------------------------------------
    # Output
    # ---------------------------------------------------------------

    print("\n" + "=" * 70)
    print("RESULT")
    print("=" * 70)

    print(f"\nStatus: {result['status']}")
    print(f"Decision: {result['decision']}")
    print(f"Win probability: {result['win_probability']:.3f}")

    if result["status"] == "DRAFTED":

        print(f"Model: {result['model']}")

        print(
            "\nRetrieved chunk IDs:",
            ", ".join(result["retrieved_chunk_ids"])
        )

        print("\n" + "-" * 70)
        print("GENERATED EVIDENCE RESPONSE")
        print("-" * 70)

        print(result["draft"])

    else:

        print("\nNote:")
        print(result["note"])

    print("\n" + "=" * 70)